args:
    index: subject
    columns: clinical_variable
    values: value
    extra: 
        - group
    use_index: False

overview: #section
    clinical variables:
        data: clinical variables 
        analyses: []
        plots:
            - basicTable
        args: 
            title: 'List of clinical variables'
    measurement matrix:
        data: preprocessed
        analyses: []
        plots: 
            - violinplot
            - basicTable
        args:
            group: group
            x_title: clinical variables
            y_title: value
            title: 'Clinical variables measurements per group'
    comparison:
        data: preprocessed
        analyses: 
            - anova
        plots: 
            - basicTable
        args:
            alpha: 0.05
            fc: 2.0
            permutations: 0
            group: group
            colorscale: Blues
            showscale: False
            marker_size: 10
            x_title: logFC
            y_title: -log(pvalue)
            drop_cols: [] 
            name: clinical_variable
            title: 'Volcano plot'
