args:
    subject_id: subject
    sample_id: biological_sample
    group_id: group
    imputation_method: KNN
    columns: clinical_variable
    values: value
    extra: 
        - group
overview: #section
    clinical variables:
        data: clinical variables 
        analyses: []
        plots:
            - basicTable
        args: 
            title: 'List of clinical variables'
    measurement matrix:
        data: processed
        analyses: []
        plots: 
            - violinplot
            - basicTable
        args:
            group: group
            x_title: clinical variables
            y_title: value
            title: 'Clinical variables measurements per group'
    comparison:
        data: processed
        analyses: 
            - anova
        plots: 
            - basicTable
        store_analysis: True
        args:
            alpha: 0.05
            fc: 2.0
            permutations: 0
            group: group
            subject: subject
            colorscale: Blues
            showscale: False
            marker_size: 10
            x_title: logFC
            y_title: -log(pvalue)
            drop_cols:
                - subject
                - biological_sample
            name: clinical_variable
            title: 'Volcano plot'
