args:
    imputation: True
    imputation_method: mixed
overview: #section
    peptides:
        data: number of peptides 
        analyses: []            
        plots: 
            - barplot
            - basicTable
        args: 
            x: x
            y: y
            height: 700
            width: 900
            group: group
            x_title: Analytical sample
            y_title: number of peptides
            title: 'Number of peptides identified per group'
    proteins:
        data: number of proteins
        analyses: []
        plots: 
            - barplot
            - basicTable
        args:
            x: x
            y: y
            height: 700
            width: 900
            group: group
            x_title: Analytical sample
            y_title: number of proteins
            title: 'Number of proteins identified per group'
    modifications:
        data: number of modified proteins
        analyses: []
        plots: 
            - facetplot
            - basicTable
        args: 
            x: x
            y: y
            group: group
            class: type
            x_title: Analytical sample
            y_title: number of modified proteins
            plot_type: bar
            title: 'Number of modified proteins identified per type'
    ranking:
        data: processed
        analyses: 
            - long_format
        plots:
            - ranking
        args:
            drop_columns: 
                - sample
                - subject
            columns:
                - name
                - y
            group: group
            index: True
            x_title: Ranking of proteins
            y_title: log2 LFQ intensity
            size: 9
            height: 900
            width: 1500
            title: Protein ranking
"data exploration":
    stratification:
        data: processed
        analyses: 
            - pca 
            #- tsne
            #-   umap
        plots:
            - pca
        args: 
            x_title: PC1
            y_title: PC2
            components: 2
            perplexity: 40
            n_iter: 1000
            init: 'pca'
            width: 1000
            height: 700
            loadings: 15
            title: 'Sample stratification'
    regulation:
        data: processed
        analyses: 
            - repeated_measurements_anova
        plots: 
            - basicTable
            - volcanoplot
        args: 
            alpha: 0.05
            fc: 2.0
            group: group
            subject: subject
            permutations: 0
            colorscale: Blues
            showscale: False
            marker_size: 10
            x_title: logFC
            y_title: -log(pvalue)
            drop_cols:
                - sample
            name: name
            title: 'Differential regulation ANOVA'
    correlation:
        data: processed
        analyses:
            - rm_correlation
        plots:
            - basicTable
            - network
            - clustergrammer
        store_analysis: True
        args:
            source: node1
            target: node2
            title: 'Features correlation network'
            format: edgelist
            values: weight
            subject: subject
            dist: False
            node_properties: {}
            width: 1600
            height: 1600
            maxLinkWidth: 6
            maxRadius: 20
            node_size: 'degree'
            cutoff: 0.5
            cutoff_abs: True
            communities_algorithm: louvain
    drug_associations:
        data: regulated
        analyses: []
        plots:
            - basicTable
        args:
            use:
                columns: identifiers
            height: 700
            width: 900
            title: 'List of drugs targetting differentially regulated proteins'
    disease_associations:
        data: regulated
        analyses: []
        plots:
            - basicTable
        args:
            use:
                columns: identifiers
            height: 700
            width: 900
            title: 'List of diseases associated with the differentially regulated proteins'
