data exploration:
    wgcna:
        data:
            proteomics: processed
            clinical: processed
        analyses:
            - wgcna
        plots:
            - wgcnaplots
        args:
            drop_cols_exp:
                - group
                - sample
            drop_cols_cli:
                - index
                - group
                - biological_sample
            RsquaredCut: 0.8
            networkType: 'unsigned'
            minModuleSize: 30
            deepSplit: 2
            pamRespectsDendro: False
            merge_modules: True
            MEDissThres: 0.25
            verbose: 0
