args:
    imputation: True
    imputation_method: mixed 
overview: #section
    peptides:
        data: number of peptides
        analyses: []
        plots:
            - barplot
            - basicTable
        args:
            x: x
            y: y
            group: group
            width: 900
            height: 700
            x_title: Analytical sample
            y_title: number of peptides
            title: 'Number of peptides identified per group'
    proteins:
        data: number of proteins
        analyses: []
        plots:
            - barplot
            - basicTable
        args:
            x: x
            y: y
            group: group
            width: 900
            height: 700
            x_title: Analytical sample
            y_title: number of proteins
            title: 'Number of proteins identified per group'
    modifications:
        data: number of modified proteins
        analyses: []
        plots:
            - facetplot
            - basicTable
        args:
            x: x
            y: y
            group: group
            class: type
            x_title: Analytical sample
            y_title: number of modified proteins
            plot_type: bar
            title: 'Number of modified proteins identified per type'
    ranking:
        data: 
            - processed
            - protein biomarkers 
        analyses: 
            - ranking_with_markers
        plots:
            - ranking
            - basicTable
        args:
            drop_columns: 
                - sample
                - subject
            columns:
                - name
                - y
            data: processed
            markers: protein biomarkers
            identifier: identifier
            marker_of: disease
            annotate: True
            group: group
            index: True
            x_title: Ranking of proteins
            y_title: log2 LFQ intensity
            size: 9
            height: 900
            width: 1500
            title: Protein ranking
    coefficient_variation:
        data: processed
        analyses:
            - coefficient_of_variation
        plots:
            - scatterplot_matrix
        args:
            drop_columns:
                - sample
                - subject
            columns:
                - name
                - y
            group: group
            index: True
            x_title: '%CV'
            y_title: log2 LFQ intensity
            size: 9
            height: 900
            width: 1500
            title: 'Proteins %CV'
data exploration:
    stratification:
        data: processed
        analyses:
            - pca
            #- tsne
            #- umap
        plots:
            - pca
        args:
            x_title: PC1
            y_title: PC2
            components: 2
            perplexity: 40
            n_iter: 1000
            init: 'pca'
            width: 1000
            height: 700
            loadings: 15
            title: 'Sample stratification'
    regulation:
        data: processed
        analyses:
            - anova
        plots:
            - basicTable
            - volcanoplot
        store_analysis: True
        args:
            alpha: 0.05
            fc: 2.0
            group: 'group'
            subject: subject
            colorscale: 'Blues'
            showscale: False
            marker_size: 10
            x_title: logFC
            y_title: -log(pvalue)
            drop_cols:
                - sample
                - subject
            name: name
            title: 'Differential regulation ANOVA'
    go_enrichment:
        data: 
            - regulation table
            - go annotation
        analyses:
            - enrichment
        plots:
            - basicTable
        store_analysis: False
        args:
            regulation_data: regulation table
            annotation: go annotation
            identifier: identifier
            groups:
                - group1
                - group2
            annotation_type: Biological_processes
            annotation_col: annotation
            reject_col: rejected
            method: fisher
            title: 'Gene Ontology Enrichment'
    pathway_enrichment:
        data: 
            - regulation table
            - pathway annotation
        analyses:
            - enrichment
        plots:
            - basicTable
        store_analysis: False
        args:
            regulation_data: regulation table
            annotation: pathway annotation
            identifier: identifier
            groups:
                - group1
                - group2
            annotation_type: Pathways
            annotation_col: annotation
            reject_col: rejected
            method: fisher
            title: 'Pathway Enrichment'
    #"topological data analysis":
    #    data: regulated
    #    analyses:
    #        - mapper
    #    plots:
    #        - mapper
    #    args:
    #        n_cubes: 15
    #        overlap: 0.5
    #        n_clusters: 3
    #        linkage: complete
    #        affinity: correlation
