args:
    imputation: True
    imputation_method: mixed
overview: #section
    peptides:
        data: number of peptides
        analyses: []
        plots:
            - barplot
            - basicTable
        args:
            x: x
            y: y
            height: 700
            width: 900
            group: group
            width: 900
            height: 700
            x_title: Analytical sample
            y_title: number of peptides
            title: 'Number of peptides identified per group'
    proteins:
        data: number of proteins
        analyses: []
        plots:
            - barplot
            - basicTable
        args:
            x: x
            y: y
            height: 700
            width: 900
            group: group
            width: 900
            height: 700
            x_title: Analytical sample
            y_title: number of proteins
            title: 'Number of proteins identified per group'
    modifications:
        data: number of modified proteins
        analyses: []
        plots:
            - facetplot
            - basicTable
        args:
            x: x
            y: y
            group: group
            class: type
            x_title: Analytical sample
            y_title: number of modified proteins
            plot_type: bar
            title: 'Number of modified proteins identified per type'
    ranking:
        data: protein_biomarkers
        analyses: []
        plots:
            - ranking_plot
        args:
            x: x
            y: y
            group: group
            highlight: is_biomarker
            x_title: rank of identified proteins
            y_title: intensity
            title: 'Ranking of proteins'
data exploration:
    ranking:
        data: preprocessed
        analyses: 
            - long_format
        plots:
            - ranking
        args:
            drop_columns: 
                - sample
                - subject
            columns:
                - x
                - name
                - y
            group: group
            x_title: Ranking of proteins
            y_title: log2 LFQ intensity
            height: 700
            width: 900
            title: Protein ranking
    stratification:
        data: preprocessed
        analyses:
            - pca
            #- tsne
            #- umap
        plots:
            - scatterplot
        args:
            x_title: PC1
            y_title: PC2
            components: 2
            perplexity: 40
            n_iter: 1000
            init: 'pca'
            width: 900
            height: 700
            title: 'Sample stratification'
    regulation:
        data: preprocessed
        analyses:
            - anova
        plots:
            - basicTable
            - volcanoplot
        args:
            alpha: 0.05
            fc: 2.0
            group: 'group'
            colorscale: 'Blues'
            showscale: False
            marker_size: 10
            x_title: logFC
            y_title: -log(pvalue)
            drop_cols:
                - sample
                - subject
            name: name
            title: 'Volcano plot'
    correlation:
        data: regulated
        analyses:
            - correlation
        plots:
            - heatmap
            - network
        args:
            source: node1
            target: node2
            title: 'Features correlation map'
            format: edgelist
            values: weight
            dist: False
            node_properties: {}
            width: 1600
            height: 1600
            maxLinkWidth: 6
            maxRadius: 20
            node_size: 'ev_centrality'
            cutoff: 0.5
            cutoff_abs: True
    interaction:
        data: regulated
        analyses: []
        plots:
            - network
        args:
            use:
                columns: identifiers
            source: node1
            target: node2
            title: 'Protein-Protein interaction network'
            format: edgelist
            values: score
            dist: False
            node_properties: {}
            width: 1600
            height: 1600
            maxLinkWidth: 7
            maxRadius: 20
            node_size: 'ev_centrality'
    # enrichment:
    #     data: regulated
    #     analyses:
    #         - enrichment
    #     plots:
    #         - basicTable
    #     args:
    #         use:
    #             columns: identifiers
    #         source: node1
    #         target: node2
    #         title: 'Protein-Protein interaction network'
    #         format: edgelist
    #         values: score
    #         dist: False
    #         node_properties: {}
    #"topological data analysis":
    #    data: regulated
    #    analyses:
    #        - mapper
    #    plots:
    #        - mapper
    #    args:
    #        n_cubes: 15
    #        overlap: 0.5
    #        n_clusters: 3
    #        linkage: complete
    #        affinity: correlation
