version: 1.0
ckg_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/ckg"
data_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data"
archive_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/archive"
databases_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/databases"
experiments_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/experiments"
ontologies_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/ontologies"
users_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/users"
stats_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/stats"
downloads_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/downloads"
reports_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/reports"
tmp_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/tmp"
imports_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/imports"
imports_databases_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/imports/databases"
imports_experiments_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/imports/experiments"
imports_ontologies_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/imports/ontologies"
imports_users_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/imports/users"
imports_curated_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/data/imports/curated"
log_directory: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/log"
report_manager_log: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/ckg/config/report_manager_log.config"
graphdb_connector_log: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/ckg/config/graphdb_connector_log.config"
graphdb_builder_log: "C:/Users/sande/work/Multi_Omics_Analytics_Department/CKG/ckg/config/graphdb_builder_log.config"
